# This file was generated by GoReleaser. DO NOT EDIT.
class Imgcat < Formula
  desc "Tool to output images in the terminal"
  homepage "https://github.com/trashhalo/imgcat"
  version "1.0.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/trashhalo/imgcat/releases/download/v1.0.2/imgcat_1.0.2_Darwin_x86_64.tar.gz"
    sha256 "f8a172e906d29612867c324cb89e0825c60a95db9d88abc6815ce128ebf18c34"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/trashhalo/imgcat/releases/download/v1.0.2/imgcat_1.0.2_Linux_x86_64.tar.gz"
      sha256 "6ef8069c995bee68b0ee1a23abb6f4d69e96980c66b12707d81feb9a974d4a80"
    end
  end

  def install
    bin.install "imgcat"
  end

  test do
    system "#{bin}/imgcat"
  end
end
