# This file was generated by GoReleaser. DO NOT EDIT.
class Imgcat < Formula
  desc "Tool to output images in the terminal"
  homepage "https://github.com/trashhalo/imgcat"
  version "1.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/trashhalo/imgcat/releases/download/v1.0.1/imgcat_1.0.1_Darwin_x86_64.tar.gz"
    sha256 "dec03f1ee5b040bcb0726007799e9302e6bb3e65d6274317ac5a6e04153688c8"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/trashhalo/imgcat/releases/download/v1.0.1/imgcat_1.0.1_Linux_x86_64.tar.gz"
      sha256 "1df33c4fe0cedf0af6f16b85b1994af0ca840bee7d7334242baa11cb220cd6bd"
    end
  end

  def install
    bin.install "imgcat"
  end

  test do
    system "#{bin}/imgcat"
  end
end
