# This file was generated by GoReleaser. DO NOT EDIT.
class Readcli < Formula
  desc "Tool to that lets you read website content* on the command line"
  homepage "https://github.com/trashhalo/readcli"
  version "0.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/trashhalo/readcli/releases/download/v0.0.1/readcli_0.0.1_Darwin_x86_64.tar.gz"
    sha256 "65ff5565d5c4262e92acf4ec53ad3966c38707cc05ecb5034cbf56458dadd462"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/trashhalo/readcli/releases/download/v0.0.1/readcli_0.0.1_Linux_x86_64.tar.gz"
      sha256 "b005e3dcd7148f06e1ac8249e61a9e8691e52e9ba096c7baef45f8e120c8886e"
    end
  end

  def install
    bin.install "readcli"
  end

  test do
    system "#{bin}/readcli"
  end
end
